=== saxomoose/person-json-schema/output/schemas/given_name_lineage.json
{
  "$id": "given_name_lineage",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "subject",
    "attribute",
    "evaluationTime",
    "lineage"
  ],
  "properties": {
    "subject": {
      "type": "object",
      "required": [
        "identifier",
        "type"
      ],
      "properties": {
        "identifier": {
          "type": "string",
          "$id": "InszNumber"
        },
        "type": {
          "type": "string",
          "const": "RegisteredNaturalPerson"
        }
      }
    },
    "attribute": {
      "type": "object",
      "required": [
        "attribute"
      ],
      "properties": {
        "attribute": {
          "type": "string",
          "const": "GivenName"
        }
      }
    },
    "evaluationTime": {
      "type": "string",
      "$id": "DateTime",
      "format": "datetime"
    },
    "lineage": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "allOf": [
              {
                "allOf": [
                  {
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "identifier",
                          "occurenceTime"
                        ],
                        "properties": {
                          "identifier": {
                            "type": "string",
                            "$id": "Identifier"
                          },
                          "occurenceTime": {
                            "anyOf": [
                              {
                                "type": "string",
                                "$id": "DateTime",
                                "format": "datetime"
                              },
                              {
                                "type": "string",
                                "$id": "Date",
                                "format": "date-time"
                              },
                              {
                                "type": "string",
                                "$id": "Month"
                              },
                              {
                                "type": "string",
                                "$id": "Year"
                              }
                            ],
                            "$id": "TemporalPosition"
                          }
                        }
                      }
                    ],
                    "$id": "LegalEvent"
                  }
                ],
                "$id": "LegalAct"
              },
              {
                "type": "object",
                "required": [
                  "eventType",
                  "legalCase"
                ],
                "properties": {
                  "eventType": {
                    "type": "string",
                    "const": "GivenNameChangeRequest"
                  },
                  "legalCase": {
                    "type": "object",
                    "required": [
                      "identifier"
                    ],
                    "properties": {
                      "identifier": {
                        "type": "string",
                        "$id": "Identifier"
                      }
                    }
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "oldValue",
                  "newValue",
                  "effectivtyStart"
                ],
                "properties": {
                  "oldValue": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "$id": "GivenName"
                  },
                  "newValue": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "$id": "GivenName"
                  },
                  "effectivtyStart": {
                    "anyOf": [
                      {
                        "type": "string",
                        "$id": "DateTime",
                        "format": "datetime"
                      },
                      {
                        "type": "string",
                        "$id": "Date",
                        "format": "date-time"
                      },
                      {
                        "type": "string",
                        "$id": "Month"
                      },
                      {
                        "type": "string",
                        "$id": "Year"
                      }
                    ],
                    "$id": "TemporalPosition"
                  }
                }
              }
            ],
            "$id": "GivenNameChangeRequest"
          },
          {
            "allOf": [
              {
                "allOf": [
                  {
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "identifier",
                          "occurenceTime"
                        ],
                        "properties": {
                          "identifier": {
                            "type": "string",
                            "$id": "Identifier"
                          },
                          "occurenceTime": {
                            "anyOf": [
                              {
                                "type": "string",
                                "$id": "DateTime",
                                "format": "datetime"
                              },
                              {
                                "type": "string",
                                "$id": "Date",
                                "format": "date-time"
                              },
                              {
                                "type": "string",
                                "$id": "Month"
                              },
                              {
                                "type": "string",
                                "$id": "Year"
                              }
                            ],
                            "$id": "TemporalPosition"
                          }
                        }
                      }
                    ],
                    "$id": "LegalEvent"
                  }
                ],
                "$id": "LegalAct"
              },
              {
                "type": "object",
                "required": [
                  "eventType",
                  "legalCase"
                ],
                "properties": {
                  "eventType": {
                    "type": "string",
                    "const": "GivenNameChangeOutcome"
                  },
                  "legalCase": {
                    "type": "object",
                    "required": [
                      "identifier"
                    ],
                    "properties": {
                      "identifier": {
                        "type": "string",
                        "$id": "Identifier"
                      }
                    }
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "oldValue",
                  "newValue",
                  "effectivtyStart"
                ],
                "properties": {
                  "oldValue": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "$id": "GivenName"
                  },
                  "newValue": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "$id": "GivenName"
                  },
                  "effectivtyStart": {
                    "anyOf": [
                      {
                        "type": "string",
                        "$id": "DateTime",
                        "format": "datetime"
                      },
                      {
                        "type": "string",
                        "$id": "Date",
                        "format": "date-time"
                      },
                      {
                        "type": "string",
                        "$id": "Month"
                      },
                      {
                        "type": "string",
                        "$id": "Year"
                      }
                    ],
                    "$id": "TemporalPosition"
                  }
                }
              }
            ],
            "$id": "GivenNameChangeOutcome"
          }
        ]
      }
    }
  }
}

=== saxomoose/person-json-schema/output/examples/given_name_lineage.json
{
  "subject": {
    "identifier": "123456789",
    "type": "RegisteredNaturalPerson"
  },
   "attribute": {
    "attribute": "GivenName"
  },
  "evaluationTime": "2026-09-04T00:00:00Z",
  "lineage": [
    {
      "identifier": "request-001",
      "occurenceTime": "2025-05-01T00:00:00Z",
      "eventType": "GivenNameChangeRequest",
      "legalCase": {
        "identifier": "case-2025-001"
      },
      "oldValue": ["John"],
      "newValue": ["John", "James"],
      "effectivtyStart": "2025-07-01T00:00:00Z"
    },
    {
      "identifier": "outcome-001",
      "occurenceTime": "2025-06-15T00:00:00Z",
      "eventType": "GivenNameChangeOutcome",
      "legalCase": {
        "identifier": "case-2025-001"
      },
      "oldValue": ["John"],
      "newValue": ["John", "James"],
      "effectivtyStart": "2025-07-01T00:00:00Z"
    },
    {
      "identifier": "request-002",
      "occurenceTime": "2026-02-01T00:00:00Z",
      "eventType": "GivenNameChangeRequest",
      "legalCase": {
        "identifier": "case-2026-002"
      },
      "oldValue": ["John", "James"],
      "newValue": ["John James"],
      "effectivtyStart": "2026-03-16T00:00:00Z"
    },
    {
      "identifier": "outcome-002",
      "occurenceTime": "2026-03-10T00:00:00Z",
      "eventType": "GivenNameChangeOutcome",
      "legalCase": {
        "identifier": "case-2026-002"
      },
      "oldValue": ["John", "James"],
      "newValue": ["John James"],
      "effectivtyStart": "2026-03-16T00:00:00Z"
    }
  ]
}
